/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @summary This is the ds-button component for Tune DS.
     * @documentation https://^@tuneurl@^/components/ds-button
     * @status in-dev
     * @since 0.0.0
     */
    interface DsButton {
        /**
          * A text prop for the `ds-button` component.
         */
        "text"?: string;
    }
}
declare global {
    /**
     * @summary This is the ds-button component for Tune DS.
     * @documentation https://^@tuneurl@^/components/ds-button
     * @status in-dev
     * @since 0.0.0
     */
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * @summary This is the ds-button component for Tune DS.
     * @documentation https://^@tuneurl@^/components/ds-button
     * @status in-dev
     * @since 0.0.0
     */
    interface DsButton {
        /**
          * A text prop for the `ds-button` component.
         */
        "text"?: string;
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @summary This is the ds-button component for Tune DS.
             * @documentation https://^@tuneurl@^/components/ds-button
             * @status in-dev
             * @since 0.0.0
             */
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
        }
    }
}
