/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface TuneExample {
        /**
          * An example prop for the `tune-example` component.
         */
        "exampleProp"?: string;
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface HTMLTuneExampleElement extends Components.TuneExample, HTMLStencilElement {
    }
    var HTMLTuneExampleElement: {
        prototype: HTMLTuneExampleElement;
        new (): HTMLTuneExampleElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "tune-example": HTMLTuneExampleElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface TuneExample {
        /**
          * An example prop for the `tune-example` component.
         */
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "tune-example": TuneExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            /**
             * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
             * @documentation https://^@tuneurl@^/components/tune-example
             * @status in-dev
             * @since 0.0.0
             */
            "tune-example": LocalJSX.TuneExample & JSXBase.HTMLAttributes<HTMLTuneExampleElement>;
        }
    }
}
