/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface TuneExample {
        /**
          * An example prop for the `tune-example` component.
         */
        "exampleProp"?: string;
    }
}
declare global {
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface HTMLTuneExampleElement extends Components.TuneExample, HTMLStencilElement {
    }
    var HTMLTuneExampleElement: {
        prototype: HTMLTuneExampleElement;
        new (): HTMLTuneExampleElement;
    };
    interface HTMLElementTagNameMap {
        "tune-example": HTMLTuneExampleElement;
    }
}
declare namespace LocalJSX {
    /**
     * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
     * @documentation https://^@tuneurl@^/components/tune-example
     * @status in-dev
     * @since 0.0.0
     */
    interface TuneExample {
        /**
          * An example prop for the `tune-example` component.
         */
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "tune-example": TuneExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @summary This is an example component for Tune DS. It is not intended to be included in our projects.
             * @documentation https://^@tuneurl@^/components/tune-example
             * @status in-dev
             * @since 0.0.0
             */
            "tune-example": LocalJSX.TuneExample & JSXBase.HTMLAttributes<HTMLTuneExampleElement>;
        }
    }
}
